---
- name: Installation and configuration of apache2
  hosts: all
  tasks:
    - name: install httpd server
      yum:
        name: httpd
        state: present
    - name: start httpd service
      service:
        name: httpd
        state: started
    - name: set server1 timezone
      community.general.timezone:
        name: Africa/Lagos
    - name: display my hostname
      shell: echo "<h2>This is my $(hostname -f) and the date is $(date)</h2>" > /var/www/html/index.html
    - name: restart httpd service
      service:
        name: httpd
        state: restarted
